require_relative '../board'
require_relative '../player'
require_relative '../human_player'
require_relative '../computer_player'
require_relative '../game_controller.rb'
require_relative '../game_view.rb'
require_relative '../game_model.rb'